version: '3.8'

services:
  # The Flask Application Service (Web Server)
  web:
    build: .
    network_mode: "host"
    env_file:
      - .env
    # The command to start the Gunicorn web server, using the config file
    # It looks for the 'app' variable in the 'site' module (site.py)
    command: ["gunicorn", "-c", "gunicorn.conf.py", "wsgi:app"]
    deploy:
      resources:
        limits:
          memory: 250M

  scheduler:
    build: .
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - web
    command: [ "celery", "-A", "app.celery_app.celery", "beat", "-l", "debug" ]
    deploy:
      resources:
        limits:
          memory: 75M

  worker:
    build: .
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - web
    command: [ "celery", "-A", "run_celery.celery", "worker", "-l", "debug" ]
    deploy:
      resources:
        limits:
          memory: 425M