version: '3.8'

services:
  # The Flask Application Service (Web Server)
  web:
    build: .
    ports:
      - "80:5000"
    env_file:
      - .env
    # The command to start the Gunicorn web server, using the config file
    # It looks for the 'app' variable in the 'site' module (site.py)
    command: ["gunicorn", "-c", "gunicorn.conf.py", "wsgi:app"]
    deploy:
      resources:
        limits:
          memory: 250M

  scheduler:
    build: .
    env_file:
      - .env
    depends_on:
      - web
    command: [ "celery", "-A", "app.celery_app.celery", "beat", "-l", "info" ]
    deploy:
      resources:
        limits:
          memory: 75M

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - web
    command: [ "celery", "-A", "run_celery.celery", "worker", "-l", "info" ]
    deploy:
      resources:
        limits:
          memory: 350M

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  redis_data: