# fly.toml app configuration file generated for py-lolesports-api on 2025-06-16T00:12:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'py-lolesports-api'
primary_region = 'dfw'

# This section tells Fly how to build your Docker image. It's usually correct by default.
[build]

# This defines the public-facing web service
[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Scales to 0 on free plan when idle
  processes = ["web"] # This service will run the 'web' process defined below

# This section defines all the different commands your app can run
[processes]
  web       = "gunicorn -c gunicorn.conf.py wsgi:app"
  scheduler = "celery -A app.celery_app.celery beat -l info"
  worker    = "celery -A run_celery.celery worker -l info"