services:
  # 1. The PostgreSQL Database Service
  # Use the dedicated 'db' type for managed PostgreSQL
  - type: db
    name: myapp-db
    postgresMajorVersion: 16
    plan: free

  # 2. The Redis Cache & Celery Broker Service
  # Use the dedicated 'redis' type for managed Redis
  - type: redis
    name: myapp-redis
    plan: free

  # 3. The Flask Web Service (Gunicorn)
  - type: web
    name: myapp-web
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "gunicorn -c gunicorn.conf.py wsgi:app"
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: DATABASE_URL
        fromService:
          type: db # Corrected type
          name: myapp-db
          property: connectionString
      - key: CACHE_REDIS_URL
        fromService:
          type: redis # Corrected type
          name: myapp-redis
          property: connectionString
      - key: CELERY_BROKER_URL # Celery also needs the Redis URL
        fromService:
          type: redis # Corrected type
          name: myapp-redis
          property: connectionString

  # 4. The Celery Beat Scheduler (Background Worker)
  - type: worker
    name: myapp-scheduler
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "celery -A app.celery_app.celery beat -l info"
    envVars:
      - fromGroup: myapp-env # Reference the shared environment group below

  # 5. The Celery Worker (Background Worker)
  - type: worker
    name: myapp-worker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "celery -A run_celery.celery worker -l info"
    envVars:
      - fromGroup: myapp-env # Reference the shared environment group below

# Define a group of environment variables to share between services
envVarGroups:
  - name: myapp-env
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        fromService:
          type: web
          name: myapp-web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromService:
          type: db # Corrected type
          name: myapp-db
          property: connectionString
      - key: CACHE_REDIS_URL
        fromService:
          type: redis # Corrected type
          name: myapp-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis # Corrected type
          name: myapp-redis
          property: connectionString
