# Define a group of environment variables to share between services
envVarGroups:
  - name: myapp-env
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: DATABASE_URL
        fromDatabase: # Use 'fromDatabase' to reference the PostgreSQL service
          name: myapp-db
          property: connectionString
      - key: CACHE_REDIS_URL
        fromService: # Use 'fromService' for other services like Redis
          type: redis
          name: myapp-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: myapp-redis
          property: connectionString

services:
  # 1. The Redis Cache & Celery Broker Service
  - type: redis
    name: myapp-redis
    plan: free

  # 2. The Flask Web Service (Gunicorn)
  - type: web
    name: myapp-web
    plan: free
    dockerfilePath: ./Dockerfile 
    dockerCommand: "gunicorn -c gunicorn.conf.py wsgi:app"
    envVars:
      - fromGroup: myapp-env # Reference the shared environment group

  # 3. The Celery Beat Scheduler (Background Worker)
  - type: worker
    name: myapp-scheduler
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "celery -A app.celery_app.celery beat -l info"
    envVars:
      - fromGroup: myapp-env # Reference the shared environment group

  # 4. The Celery Worker (Background Worker)
  - type: worker
    name: myapp-worker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "celery -A run_celery.celery worker -l info"
    envVars:
      - fromGroup: myapp-env # Reference the shared environment group

# Define managed databases separately from other services
databases:
  # 5. The PostgreSQL Database Service
  - name: myapp-db
    plan: free
    postgresMajorVersion: 16